### ISSUE TITLE
Add support for multiple files

### ISSUE THREAD

**Issue by selbekk** [greena13/react-simple-file-input#2]
If you set the `multiple` attribute, you can select several files. Right now, the first file is always chosen, and there's no way to get to the remaining ones. I fixed it in my local fork of this, but only for the `onChange` event.

I'd love to create a pull request that does this for all, but then I need to know that this is actually maintained.

**Comment by greena13** [comment]
Thanks for your attention on this, selbekk. This is one of a few issues I am aware of. I am planning on cycling back to this repository and giving it more of my attention in the near future, but I welcome any fix that you have created.

**Comment by selbekk** [comment]
Hi there! Created a very simple pull request that would address the issue, but I'm not sure if there's a few things missing - like "all files read" etc. Would love your input on it!

**Comment by greena13** [comment]
Addressed in v1.0.0
